EXPERIMENT:
  NAME: ""
  TAG: "cam,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CAM"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
CAM:
  LOSS:
#     FEAT_WEIGHT: 1.5
    FEAT_WEIGHT: 200.
